# Generated by Django 4.2.1 on 2023-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myresume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=70)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_subject', models.CharField(max_length=500)),
                ('your_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
